on:
  - pull_request
  - push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: ESLint
        run: |
          yarn --frozen-lockfile
          yarn eslint .

  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn pack
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: '*.tgz'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: |
          yarn --frozen-lockfile
          yarn test

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Prettier
        run: |
          yarn --frozen-lockfile
          yarn prettier .

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: TypeScript
        run: |
          yarn --frozen-lockfile
          yarn tsc

  release:
    runs-on: ubuntu-latest
    needs: [eslint, test, pack, prettier, tsc]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-node@v2
        with: { node-version: 14 }
      - uses: actions/download-artifact@v2
        with: { name: package }
      - run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
