name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn --frozen-lockfile
      - run: yarn eslint .

  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn --frozen-lockfile
      - run: yarn pack
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: '*.tgz'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn --frozen-lockfile
      - run: yarn test

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn --frozen-lockfile
      - run: yarn prettier --check .

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn --frozen-lockfile
      - run: yarn tsc

  release:
    runs-on: ubuntu-latest
    needs: [eslint, test, pack, prettier, tsc]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - uses: actions/download-artifact@v2
        with: { name: package }
      - run: npm publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
